Upload only 3lap 1
SpeedRunTooked/mk64-watcher pull request #4
Opened 2022-06-27 06:21 UTC by salvoch

Changed mk64.py to upload only the fastest 3-lap record instead of any top 5 record.

2022-06-27 06:22 UTC, gabranches commented
LGTM 👍

2022-06-28 03:33 UTC, jmct requested changes
Code is simpler, which is always nice!

Just add back the explanation of why we only check whether `nr_re` is `None`. It might be obvious to us now, but it took a bit of thinking on the day and future us won't remember.

2022-06-28 03:33 UTC, jmct commented on src/utils/mk64.py
> +            # Commented these out because not being used atm
Why'd you keep these comments (that represent code we don't need), but delete the explanatory comments?

2022-06-28 04:23 UTC, jmct approved these changes
Awesome, thanks!

2022-06-28 04:23 UTC, merged